-- MySQL Script generated by MySQL Workbench
-- 01/04/17 22:12:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema watking_test1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema watking_test1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `watking_test1` DEFAULT CHARACTER SET latin2 ;
USE `watking_test1` ;

-- -----------------------------------------------------
-- Table `watking_test1`.`COURT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`court` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`court` (
  `ID` INT(11) NOT NULL,
  `NAME` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `watking_test1`.`EVENT_TYPE_DICT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`event_type_dict` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`event_type_dict` (
  `ID` INT(11) NOT NULL,
  `EVENT_NAME` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `watking_test1`.`REFEREE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`referee` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`referee` (
  `ID` INT(11) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `BIRTH_DATE` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `watking_test1`.`PLAYER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`player` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`player` (
  `ID` INT(11) NOT NULL,
  `NAME` VARCHAR(45) NULL DEFAULT NULL,
  `TEAM_ID` INT(11) NULL DEFAULT NULL,
  `NATIONALITY` VARCHAR(45) NULL DEFAULT NULL,
  `POSITION` VARCHAR(45) NULL DEFAULT NULL,
  `DATE_OF_BIRTH` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PLAYER_TEAM1_idx` (`TEAM_ID` ASC),
  CONSTRAINT `fk_PLAYER_TEAM1`
    FOREIGN KEY (`TEAM_ID`)
    REFERENCES `watking_test1`.`TEAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `watking_test1`.`TEAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`team` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`team` (
  `ID` INT(11) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `FAUNDATION_DATE` DATE NULL DEFAULT NULL,
  `CAPITAIN_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TEAM_PLAYER1_idx` (`CAPITAIN_ID` ASC),
  CONSTRAINT `fk_TEAM_PLAYER1`
    FOREIGN KEY (`CAPITAIN_ID`)
    REFERENCES `watking_test1`.`PLAYER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `watking_test1`.`MATCH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`match` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`match` (
  `ID` INT(11) NOT NULL,
  `MATCH_DATE` DATE NULL DEFAULT NULL,
  `TEAM_HOME_ID` INT(11) NOT NULL,
  `TEAM_AWAY_ID` INT(11) NOT NULL,
  `REFEREE_ID` INT(11) NOT NULL,
  `COURT_ID` INT(11) NOT NULL,
  `IS_FINISHED` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `fk_MATCH_TEAM1_idx` (`TEAM_HOME_ID` ASC),
  INDEX `fk_MATCH_TEAM2_idx` (`TEAM_AWAY_ID` ASC),
  INDEX `fk_MATCH_REFEREE1_idx` (`REFEREE_ID` ASC),
  INDEX `fk_MATCH_COURT1_idx` (`COURT_ID` ASC),
  CONSTRAINT `fk_MATCH_COURT1`
    FOREIGN KEY (`COURT_ID`)
    REFERENCES `watking_test1`.`COURT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATCH_REFEREE1`
    FOREIGN KEY (`REFEREE_ID`)
    REFERENCES `watking_test1`.`REFEREE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATCH_TEAM1`
    FOREIGN KEY (`TEAM_HOME_ID`)
    REFERENCES `watking_test1`.`TEAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATCH_TEAM2`
    FOREIGN KEY (`TEAM_AWAY_ID`)
    REFERENCES `watking_test1`.`TEAM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;


-- -----------------------------------------------------
-- Table `watking_test1`.`MATCH_EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watking_test1`.`match_event` ;

CREATE TABLE IF NOT EXISTS `watking_test1`.`match_event` (
  `ID` INT(11) NOT NULL,
  `EVENT_VALUE` DECIMAL(10,0) NULL DEFAULT NULL,
  `EVENT_MINUTE` INT(11) NULL DEFAULT NULL,
  `MATCH_ID` INT(11) NOT NULL,
  `EVENT_TYPE_ID` INT(11) NOT NULL,
  `PLAYER_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MATCH_EVENT_MATCH1_idx` (`MATCH_ID` ASC),
  INDEX `fk_MATCH_EVENT_EVENT_TYPE_DICT1_idx` (`EVENT_TYPE_ID` ASC),
  INDEX `fk_MATCH_EVENT_PLAYER1_idx` (`PLAYER_ID` ASC),
  CONSTRAINT `fk_MATCH_EVENT_EVENT_TYPE_DICT1`
    FOREIGN KEY (`EVENT_TYPE_ID`)
    REFERENCES `watking_test1`.`EVENT_TYPE_DICT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATCH_EVENT_MATCH1`
    FOREIGN KEY (`MATCH_ID`)
    REFERENCES `watking_test1`.`MATCH` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATCH_EVENT_PLAYER1`
    FOREIGN KEY (`PLAYER_ID`)
    REFERENCES `watking_test1`.`PLAYER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin2;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
