CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `watking_prime`@`%` 
    SQL SECURITY DEFINER
VIEW `TABELA_PUNKTOWA` AS
    SELECT 
        `TABELA_LIGOWA_POMOCNICZA`.`Name` AS `Name`,
        SUM(`TABELA_LIGOWA_POMOCNICZA`.`Pkt`) AS `Punkty`
    FROM
        `TABELA_LIGOWA_POMOCNICZA`
    WHERE
        (`TABELA_LIGOWA_POMOCNICZA`.`Name` IS NOT NULL)
    GROUP BY `TABELA_LIGOWA_POMOCNICZA`.`Name`
    ORDER BY 2 DESC