CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `watking_prime`@`%` 
    SQL SECURITY DEFINER
VIEW `LEAGUE_TABLE` AS
    SELECT 
        `TEAMS_UNIT_POINTS`.`LEAGUE_ID` AS `LEAGUE_ID`,
        `TEAMS_UNIT_POINTS`.`TEAM_ID` AS `TEAM_ID`,
        SUM(`TEAMS_UNIT_POINTS`.`GOALS_SCORED`) AS `GOALS_SCORED`,
        SUM(`TEAMS_UNIT_POINTS`.`GOALS_LOST`) AS `GOALS_LOST`,
        SUM(`TEAMS_UNIT_POINTS`.`POINTS`) AS `POINTS`
    FROM
        `TEAMS_UNIT_POINTS`
    GROUP BY `TEAMS_UNIT_POINTS`.`TEAM_ID`
    ORDER BY `POINTS` DESC