ALTER TABLE `watking_test1`.`TEAM` 
ADD COLUMN `LEAGUE_ID` INT NULL AFTER `CAPITAIN_ID`,
ADD INDEX `fk_LEAGUE_ID_idx` (`LEAGUE_ID` ASC);
ALTER TABLE `watking_test1`.`TEAM` 
ADD CONSTRAINT `fk_LEAGUE_ID`
  FOREIGN KEY (`LEAGUE_ID`)
  REFERENCES `watking_test1`.`LEAGUE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;